# Generated by Django 6.0.5 on 2026-05-14 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=100)),
                ('num_passengers', models.PositiveIntegerField(default=1)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan Car (3 Users)'), ('noah', 'Micro Noah (7 Users)'), ('hiace_11', 'Micro Hi-Ace (11 Users)'), ('hiace_14', 'Micro Hi-Ace (14 Users)'), ('delivery_van', 'Delivery Van (Covered Van, Pickup etc.)'), ('other', 'Other')], default='sedan', max_length=20)),
                ('vehicle_type_other', models.CharField(blank=True, max_length=200)),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('pick_up_location', models.CharField(max_length=300)),
                ('destination', models.CharField(max_length=300)),
                ('drop_off_date', models.DateField()),
                ('drop_off_time', models.TimeField()),
                ('drop_off_location', models.CharField(max_length=300)),
                ('travelling_reason', models.TextField()),
                ('project_name_code', models.CharField(max_length=300)),
                ('budget_code', models.CharField(max_length=300)),
                ('supervisor_acknowledged', models.BooleanField(default=False)),
                ('comments_remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_first', 'Pending First Approval'), ('pending_second', 'Pending Second Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_first', max_length=20)),
                ('first_approved_at', models.DateTimeField(blank=True, null=True)),
                ('second_approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_first_approvals', to=settings.AUTH_USER_MODEL)),
                ('second_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_second_approvals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_requisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
