# Generated by Django 6.0.6 on 2026-10-01 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_requisition', '0005_alter_transportrequisition_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan Car (3 Users)'), ('noah', 'Micro Noah (7 Users)'), ('hiace_11', 'Micro Hi-Ace (11 Users)'), ('hiace_14', 'Micro Hi-Ace (14 Users)'), ('delivery_van', 'Delivery Van (Covered Van, Pickup etc.)'), ('other', 'Other')], max_length=20)),
                ('make_model', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Under maintenance'), ('retired', 'Retired')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
        migrations.AddField(
            model_name='transportrequisition',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transportrequisition',
            name='grants_amended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transportrequisition',
            name='grants_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportrequisition',
            name='grants_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_grants_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transportrequisition',
            name='grants_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transportrequisition',
            name='transport_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportrequisition',
            name='transport_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_admin_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transportrequisition',
            name='status',
            field=models.CharField(choices=[('pending_first', 'Pending Supervisor Approval'), ('pending_grants', 'Pending Grants Approval'), ('pending_transport', 'Pending Transport Admin'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('assigned', 'Vehicle and Driver Assigned'), ('pending_second', 'Pending Second Approval')], default='pending_first', max_length=20),
        ),
        migrations.AddField(
            model_name='transportrequisition',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='transport_requisition.vehicle'),
        ),
    ]
