# Generated by Django 6.0.4 on 2026-05-18 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_make_fields_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('batch_id', models.CharField(blank=True, default='', max_length=100)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contract')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
