# Generated by Django 6.0.6 on 2026-10-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_emailconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='default_from_email',
            field=models.CharField(default='', max_length=500),
        ),
    ]
