# Generated by Django 6.0.6 on 2026-10-01 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Long text'), ('email', 'Email'), ('tel', 'Phone'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date and time'), ('select', 'Dropdown'), ('checkbox', 'Checkbox'), ('radio', 'Radio buttons')], default='text', max_length=20)),
                ('help_text', models.TextField(blank=True)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('step', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=True, help_text='Stored in a real database column. Uncheck for fields added by an administrator, whose values are kept in the extra_data JSON blob.')),
                ('visible_to_requester', models.BooleanField(default=True)),
                ('show_in_review', models.BooleanField(default=True)),
                ('options', models.TextField(blank=True, help_text='One choice per line, as "value|Label shown to the user".')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='portal_config.module')),
            ],
            options={
                'ordering': ['module', 'step', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('approver_role', models.CharField(blank=True, choices="[('requester', 'Requester'), ('supervisor', 'Supervisor (1st Approver)'), ('grants', 'Grants (2nd Approver)'), ('grants_admin', 'Grants Admin'), ('ict_approver', 'ICT Approver (2nd Approver)'), ('ict_admin', 'ICT Admin'), ('transport_admin', 'Transport Admin'), ('internal_admin', 'Internal Admin'), ('hr_admin', 'HR Admin'), ('admin', 'Admin')]", help_text='Only users holding this role can act at this stage. Leave blank to allow any approver.', max_length=20)),
                ('actions', models.CharField(default='approve,decline', help_text='Comma-separated: approve, decline, amend, assign.', max_length=100)),
                ('require_reason_on_decline', models.BooleanField(default=True)),
                ('is_terminal', models.BooleanField(default=False, help_text='Tick for the final stage (approved / rejected / fulfilled).')),
                ('is_active', models.BooleanField(default=True)),
                ('amendable_fields', models.ManyToManyField(blank=True, help_text='Fields this stage is allowed to change before approving.', related_name='amendable_at_stages', to='portal_config.formfield')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='portal_config.module')),
            ],
            options={
                'ordering': ['module', 'order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('module', 'key'), name='unique_field_key_per_module'),
        ),
        migrations.AddConstraint(
            model_name='workflowstage',
            constraint=models.UniqueConstraint(fields=('module', 'key'), name='unique_stage_key_per_module'),
        ),
    ]
