# Generated by Django 6.0.6 on 2026-10-01 06:49

import portal_config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_config', '0002_seed_transport_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstage',
            name='approver_role',
            field=models.CharField(blank=True, choices=portal_config.models._user_role_choices, help_text='Only users holding this role can act at this stage. Leave blank to allow any approver.', max_length=20),
        ),
    ]
