# Generated by Django 6.0.5 on 2026-05-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('requester', 'Requester'), ('supervisor', 'Supervisor (1st Approver)'), ('ict_approver', 'ICT Approver (2nd Approver)'), ('admin', 'Admin')], default='requester', max_length=20),
        ),
    ]
