# Generated by Django 6.0.6 on 2026-10-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('requester', 'Requester'), ('supervisor', 'Supervisor (1st Approver)'), ('grants', 'Grants (2nd Approver)'), ('grants_admin', 'Grants Admin'), ('ict_approver', 'ICT Approver (2nd Approver)'), ('ict_admin', 'ICT Admin'), ('transport_admin', 'Transport Admin'), ('internal_admin', 'Internal Admin'), ('hr_admin', 'HR Admin'), ('admin', 'Admin')], default='requester', max_length=20),
        ),
    ]
