# Generated by Django 6.0.4 on 2026-04-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payslip',
            old_name='house_rent',
            new_name='income_tax',
        ),
        migrations.RenameField(
            model_name='payslip',
            old_name='medical_allowance',
            new_name='transport',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='other_allowance',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='other_deduction',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='provident_fund',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='transport_allowance',
        ),
    ]
