# Generated by Django 6.0.4 on 2026-04-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0003_payslip_conveyance_payslip_house_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='arrears',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='festival_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='others',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='tin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
