# Generated by Django 6.0.6 on 2026-06-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0004_payslip_arrears_payslip_festival_bonus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=50)),
                ('months', models.CharField(help_text='e.g. January, February or Jan-Feb 2026', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
