# Generated by Django 6.0.6 on 2026-06-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslip', '0005_paysliprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='paysliprequest',
            name='year',
            field=models.CharField(default='2026', max_length=4),
        ),
        migrations.AlterField(
            model_name='paysliprequest',
            name='months',
            field=models.CharField(help_text='e.g. January, February', max_length=200),
        ),
    ]
