# Generated by Django 6.0.5 on 2026-05-14 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ICTRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=200)),
                ('pin_number', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=50)),
                ('device_equipment', models.CharField(max_length=300)),
                ('equipment_specification', models.TextField(blank=True)),
                ('purpose', models.TextField()),
                ('requisition_date', models.DateField()),
                ('requirement_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('supervisor_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending_first', 'Pending First Approval'), ('pending_second', 'Pending Second Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_first', max_length=20)),
                ('first_approved_at', models.DateTimeField(blank=True, null=True)),
                ('second_approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ict_first_approvals', to=settings.AUTH_USER_MODEL)),
                ('second_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ict_second_approvals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ict_requisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
