# Generated by Django 6.0.5 on 2026-05-14 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_requisition', '0001_fresh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ictrequisition',
            name='supervisor_email',
        ),
        migrations.AddField(
            model_name='ictrequisition',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ict_supervisor_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
