# Generated by Django 6.0.5 on 2026-05-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_requisition', '0002_supervisor_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ictrequisition',
            name='device_equipment',
            field=models.TextField(),
        ),
    ]
