# Generated by Django 6.0.5 on 2026-05-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('ict', 'ICT'), ('transport', 'Transport'), ('internal', 'Internal')], max_length=20, unique=True)),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=300)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_host_user', models.CharField(max_length=300)),
                ('email_host_password', models.CharField(max_length=300)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('from_email', models.EmailField(help_text='Sender address for this department', max_length=254)),
                ('notification_email', models.EmailField(help_text='Department inbox that receives notifications', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
            },
        ),
    ]
