# Generated by Django 6.0.5 on 2026-05-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('ict', 'ICT'), ('transport', 'Transport'), ('internal', 'Internal')], max_length=20)),
                ('email_type', models.CharField(choices=[('approval_request', 'Approval Request'), ('notification', 'Status Notification')], max_length=30)),
                ('req_type', models.CharField(blank=True, max_length=20)),
                ('req_id', models.PositiveIntegerField(blank=True, null=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('success', 'Sent'), ('failed', 'Failed')], default='failed', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
