# Generated by Django 6.0.6 on 2026-06-22 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_emaillog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_type', models.CharField(choices=[('ict', 'ICT'), ('transport', 'Transport'), ('internal', 'Internal')], max_length=20)),
                ('req_id', models.PositiveIntegerField()),
                ('request_number', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(choices=[('created', 'Created'), ('pending_first', 'Pending First Approval'), ('pending_second', 'Pending Second Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
